project:
  type: website

website:
  title: "Riesgo"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dersley
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholasjohndorsch/
format:
  html:
    theme: litera
    css: styles.css
    fig-align: center



