project:
  type: website

website:
  title: "dorschblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dersley
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholasjohndorsch/
format:
  html:
    toc: true
    toc-depth: 3
    toc-location: right
    theme: darkly
    css: styles.css
    fig-align: center
    code-fold: true
    code-line-numbers: false
    title=block-banner: false
    




