project:
  type: website

website:
  title: "dorschblog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/dersley
      - icon: linkedin
        href: https://www.linkedin.com/in/nicholasjohndorsch/
format:
  html:
    theme: darkly
    css: styles.css
    fig-align: center
    title=block-banner: false




